# -*- coding: utf-8 -*-
"""Global Health Trends Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doUQyMaoZJm5PWexoIUap0O3wA9a-Z_c
"""

import pandas as pd

# Load the dataset
data = pd.read_excel('/content/data.xlsx')

# Display basic information about the dataset
print(data.info())

# Print the column names to verify if 'Country' exists
print(data.columns)


# Handle missing values
data.fillna(method='ffill', inplace=True)  # Forward fill to fill missing values

# Example of filtering data for a specific country and year
filtered_data = data[(data['whoreg6'] == 'Americas') & (data['date'] >= 2000)]

# Group by year and calculate the average life expectancy
life_expectancy_trend = filtered_data.groupby('Year')['Life Expectancy'].mean().reset_index()

# Display the trend
print(life_expectancy_trend)

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style
sns.set(style='whitegrid')

# Plotting the trend
plt.figure(figsize=(12, 6))
sns.lineplot(data=life_expectancy_trend, x='date', y='Life Expectancy')
plt.title('Average Life Expectancy in the americas (2000-2020)')
plt.xlabel('date')
plt.ylabel('Life Expectancy')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()